config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'

  get 'contacts/create'

  get '/policy' => 'document#policy', :as => 'policy'

  root 'welcomes#index'
  get '/song' => 'welcomes#song', :as => 'song'
  post 'welcomes/new' => 'welcomes#new'

  match '/contact', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  resources :welcomes

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  protect_from_forgery with: :exception

  #Including Gems
  require 'soundcloud'
  require 'whatlanguage'
  require 'twitter'

  # ************************************** INDEX **************************************
  def index
    @home_page = true

    if !session[:genre]
      session[:genre] = "music"
    end

    #List of genres
    @genre_list = list_genres
    @random_number=Random.new.rand(0..(@genre_list.size-1))

    #Twitter REST API credentials
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "c9uC8Nx2rGDvH25J1tenPi23t"
      config.consumer_secret     = "xoKs0lpvvSjawrljRv3vwCFmtk4ZqKXMWxr6eHR35tNY76fiBT"
      config.access_token        = "289016412-ISb7lTpGAKvS5HjzPj5OjwDJcfv3fEDznVlKNzR0"
      config.access_token_secret = "f4HJBzhXiIqjImSfYDWApOKwu08VtXd0PcCbB8QwF15CD"
    end

    #Searches for tweets with the word soundcloud and the genre
    @tweets_bandcamp = []
    client.search("#{@this_is_the_dropdown_value} bandcamp.com/", options = {:lang => "en"}).take(200).each do |tweet|
      @tweets_bandcamp << {:text => "#{tweet.text}", :id => tweet.id}
    end

    while @tweets_bandcamp.size<160 do
      client.search("bandcamp.com/", options = {:lang => "en"}).take(100).each do |tweet|
        @tweets_bandcamp << {:text => tweet.text, :id => tweet.id}
      end
    end

    @tweets_bandcamp.shuffle!
    @tweets_bandcamp.uniq! {|e| e[:text] }
    @tweet_text = []
    @tweet_ids  = []
    @tweets_bandcamp[0..5].each do |tweet|
      @tweet_text << tweet[:text]
      @tweet_ids  << tweet[:id]
    end
  end

  # ************************************** NEW **************************************
  def new

    #List of genres
    @genre_list = list_genres
    @random_number=Random.new.rand(0..(@genre_list.size-1))

    #Get genre from dropdown values
    begin
      if params["dropdown_cases"]
        params["dropdown_cases"].each do |cases|
          @this_is_the_dropdown_value = cases.to_s
        end
      else
        @this_is_the_dropdown_value = session[:genre]
      end
    rescue
      @this_is_the_dropdown_value = "music"
    end

    redirect_to :action => :song, :genre => @this_is_the_dropdown_value

  end


  # ************************************** SONG **************************************
  def song
    begin

      @home_page = false

      @genre_list = list_genres
      @random_number=Random.new.rand(0..(@genre_list.size-1))

      @this_is_the_dropdown_value = params[:genre]

      #Get genre from dropdown values
      begin
        if params[:genre]
          @this_is_the_dropdown_value = params[:genre]
        else
          @this_is_the_dropdown_value = session[:genre]
        end
      rescue
        @this_is_the_dropdown_value = "music"
      end

      #Twitter REST API credentials
      client = Twitter::REST::Client.new do |config|
        config.consumer_key        = "c9uC8Nx2rGDvH25J1tenPi23t"
        config.consumer_secret     = "xoKs0lpvvSjawrljRv3vwCFmtk4ZqKXMWxr6eHR35tNY76fiBT"
        config.access_token        = "289016412-ISb7lTpGAKvS5HjzPj5OjwDJcfv3fEDznVlKNzR0"
        config.access_token_secret = "f4HJBzhXiIqjImSfYDWApOKwu08VtXd0PcCbB8QwF15CD"
      end

      #Searches for tweets with the word soundcloud and the genre
      @tweets_bandcamp = []
      client.search("#{@this_is_the_dropdown_value} bandcamp.com/album/", options = {:lang => "en"}).take(200).each do |tweet|
        @tweets_bandcamp << {:text => "#{tweet.text}", :id => tweet.id}
      end

      while @tweets_bandcamp.size<160 do
        client.search("bandcamp.com/album/", options = {:lang => "en"}).take(100).each do |tweet|
          @tweets_bandcamp << {:text => tweet.text, :id => tweet.id}
        end
      end

      @tweets_bandcamp.shuffle!
      @tweets_bandcamp.uniq! {|e| e[:text] }
      @tweet_text = []
      @tweet_ids  = []

      @tweets_bandcamp[0..5].each do |tweet|
        @tweet_text << tweet[:text]
        @tweet_ids  << tweet[:id]
      end


      #Soundcloud API gets songs
      begin

        client = SoundCloud.new(:client_id => '1fc18537f83fe8005530fbac52f2b9f4')
        track = client.get('/resolve', url: "http://api.soundcloud.com/tracks/#{params[:id]}")
        @individual_tune = {id: track.uri, song_list: track.permalink_url, titles: "#{track.title}", final_id: "#{track.id}"}

        if params[:genre]
          session[:genre] = "#{params[:genre]}"
          @this_is_the_dropdown_value = "#{params[:genre]}"
        else
          session[:genre] = "#{track.genre.split(" ").first}"
          @this_is_the_dropdown_value = "#{track.genre.split(" ").first}"

        end
        
      rescue

        client = SoundCloud.new(:client_id => '1fc18537f83fe8005530fbac52f2b9f4')
        tracks = client.get('/tracks', :limit => 200, :order => 'hotness', :genres => @this_is_the_dropdown_value)
        zero_song_hash=[]
        tracks.each do |track|
          if session[:array]
            session[:array].each do |sesh|
              next if sesh.to_s == "#{track.id}"
            end
          end
          zero_song_hash << {id: track.uri, tune: track.permalink_url, 
                  name: "#{track.title}", track_id: "#{track.id}"}
        end

        zero_song_hash.shuffle!
        final_song_hash=[]
        zero_song_hash.first(5).each do |song|
          if (defined?(song[:id])).nil?
            next
          else
            if song[:name].language.to_s.eql? "english"
              final_song_hash.unshift({song_list: song[:tune], 
                titles: song[:name], final_id: song[:track_id]})
            else
              final_song_hash.push({song_list: song[:tune], 
                titles: song[:name], final_id: song[:track_id]})
            end
          end
        end

        @the_song = []
        final_song_hash.each do |piece|
          piece[:song_list].gsub! ':', '%3A'
          piece[:song_list].gsub! '/', '%2F'
          @the_song << piece
        end
        @count = 0
        @individual_tune = @the_song.first

        if !session[:genre]
          session[:genre] = "Music"
        else
          session[:genre] = "#{@this_is_the_dropdown_value}"
        end

      end

      if session[:array]
        if session[:array].size == 30
          session[:array].delete_at(29)
          session[:array].unshift @individual_tune[:final_id]
        else
          session[:array].unshift @individual_tune[:final_id]
        end
      else
        session[:array] = Array.new
      end

      # Next song session
      @number_of_next_sessions = 5

      if session[:next] && session[:next] < @number_of_next_sessions
          session[:next] += 1
        else
          session[:next] = 0
        end
      
      if !params[:genre] || params[:id]
        session[:next] = @number_of_next_sessions
      end

    rescue
      flash[:notice] = "Sorry. Something went wrong with SoundCloud"
      redirect_to(:action => 'index')
    end
  end

  private

    def list_genres
      return ["acapella", "african", "alternative", "ambient", "beats", "bluegrass", "blues", "chill", "choir", "classical", "comedy", "cover", "deep", "delta", "disco", "dub", "dubstep", "easy", "edm", "electro", "electronica", "experimental", "folk", "funk", "future", "gfunk", "gospel", "happy", "hip-hop", "house", "indie", "instrumental", "international", "irish", "jazz", "juke", "jungle", "latin", "lounge", "metal", "newage", "oldie", "opera", "poetry", "pop", "post", "post-hardcore", "prog", "progressive", "progrock", "psychedelic", "punk", "r&b", "rap", "reggae", "rock", "samba", "ska", "swing", "trance", "tribal", "triphop", "worldmusic"]
    end

end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_adsense1.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- newdisco ad -->
<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-6648262970870765" data-ad-slot="9843915732" data-ad-format="auto"></ins>
<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/welcomes/_adsense2.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-10">
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- newdisco ad -->
			<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-6648262970870765" data-ad-slot="9843915732" data-ad-format="auto"></ins>
			<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
			</script>
		</div>
		<div class="col-md-1"></div>
	</div>
</div>

app/views/welcomes/_finishing.html.erb
<%= javascript_tag do %>

	var widget = SC.Widget(document.querySelector('iframe'));

	widget.bind(SC.Widget.Events.FINISH, function() {
		document.getElementById("song").style.display="none";
		document.getElementById("loading_gif").style.display="inline";
		document.getElementById("dropdown_cases_").style.display="none";
		document.getElementById("getting_song").style.paddingTop="0px";
		<%= "window.location.href = 'http://www.newdis.co/song?genre=#{params[:genre]}';".html_safe %>
	});

<% end %>

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/_selecting.html.erb
<div id="getting_song" style="padding-top:50px;">
  <%= form_tag(new_welcome_path, method: "post") do %>
      <select id="dropdown_cases_" class="btn" name="dropdown_cases[]" style="display:inline;")>
      <%  count=0 
          @genre_list.each do |genre| %>
            <% if count==@random_number %>
                  <%= "<option value='#{genre}' selected>#{genre}</option>".html_safe %>
            <% else %>
                  <%= "<option value='#{genre}'>#{genre}</option>".html_safe %>
            <% end %>
      <%  count+=1
          end %>
      </select>
      <%= submit_tag("Get Song!", id: "song", class: "btn btn-default btn-lg", onclick: "loading();", :style => "display:inline;") %>
      <%= image_tag("loader.gif", :alt => "loading gif image", id: "loading_gif", :style => "display:none") %>
  <% end %>
</div>

app/views/welcomes/_welcome.html.erb
<article>
	<h1>New <%= @this_is_the_dropdown_value.capitalize %> Music</h1>
	<div id="prev_next">
		<%= link_to new_welcome_path, onclick: "loading_next();", onMouseover: "change_red();", onMouseout: "change_white();", :id => "next-link", :method => :post do %>
			<button type="button" id="next-button" class="btn btn-success">
				<i id="next-arrow" class="fa fa-angle-double-right fa-4x" id="right_arrows"></i>
				<p id="next-song-text">Next<br />Song!</p>
			</button>
		<% end %>
	</div>
	<%= "<iframe scrolling='no' frameborder='no' width='100%' src='https://w.soundcloud.com/player/?url=#{@individual_tune[:song_list]}&color=c1272d&show_comments=true&auto_play=true&show_artwork=true&buying=true&download=true'>".html_safe %></iframe>
	<%= render :partial => 'selecting' %>

	<% if session[:next] && session[:next] < @number_of_next_sessions %>
		<%= render :partial => 'finishing' %>
	<% end %>
</article>

app/views/welcomes/create.js.erb
$(document).ready(function(){
    $('#tune').click(function(){
        alert('Sign new href executed.');
    });
})

app/views/welcomes/edit.html.erb
<h1>Editing welcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<% if session[:genre] == "music" %>
  <div class="alert fade in alert-success ">
    <button class="close" data-dismiss="alert">&times;</button>
    <h6>Important information regarding cookies and NewDis.co</h6>
    <p class="cookies">By using this website, you consent to the use of cookies in accordance with our Policy (<%= link_to("See Here", contact_path) %>).</p>
  </div>
  <% session[:check_cookie] == 1 %>
<% end %>

<article>
  <h1>Discover</h1>
  <h3>New Music</h3>
  <%= render :partial => 'selecting' %>
</article>

<section class="well" style="display:none;">
  <div id="twitter-outer">
    <div id="twitter-button">
      <a href="https://twitter.com/intent/tweet?button_hashtag=newDisco&text=Discover New Music with me..! http://www.newdis.co" class="twitter-hashtag-button" data-related="RonanFrawley">Tweet #TwitterStories</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </div>
  </div>
  <!--<h2>The Disco Diet</h2>-->
  <% if false %>
  <p>
    <%= "#{@notice}".html_safe %>
  </p>
  <% end %>
  <h3>Do you find it hard to Discover new Music?</h3>
  <p>
    We know how tricky this can be. It's hard to move past the BS. The current institutions regard musical acts as Products... and you just want to listen to a some serious beats... 
  </p>
  <p>
    NewDisco has you covered! We will take genre information and create playlists of new music for you. Playlist are made on the fly and will feature music that you have not heard before. You can like and share songs through your social media.
  </p>
  <h3>Where does the new Music come from?</h3>
  <p>
    NewDisco uses Music sharing websites to bring you something different. These include SoundCloud, Bandcamp and LastFM. Most of the song you hear will be amateur artists. This means that everything you hear will be fresh and different!
  </p>
  <p>
    We can pretty much guarantee that you will find something you like here. If you are a member of any of these websites, you can add anything you like to your own library. You can also share new music with friends and followers
  </p>
  <p>
    Music is not a business to you. You don't consider yourself a consumer. You don't love music because of the product. NewDisco is all about your passion for <strong>Discovering</strong> new music.
  </p>
  <h3>About NewDisco</h3>
  <p id="ronan_above">
    NewDisco was built by this guy...
  </p>
  <div id="ronan">
    <a class="twitter-timeline" href="https://twitter.com/RonanFrawley" data-widget-id="506563414320099328">Tweets by @RonanFrawley</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>
</section>

app/views/welcomes/new.html.erb
<%= 'welcome' %>

app/views/welcomes/show.html.erb
<%= 'welcome' %>

app/views/welcomes/song.html.erb
<%= render :partial => 'welcome' %>